web:
  build: web/
  volumes_from:
    - testlink
  links:
    - php:php
  ports:
    - 8082:80
  environment:
    - DATABASE_HOST=db
    - DATABASE_PASS=testlink

php:
  build: php/
  ports:
    - 9002:9000
  volumes:
    - ./data/testlink-upload:/var/testlink/upload_area
    - ./data/testlink-logs:/var/testlink/logs
  volumes_from:
    - testlink
  links:
    - db:db

db:
  image: mariadb:10
  environment:
   - MYSQL_DATABASE=test
   - MYSQL_ROOT_PASSWORD=testlink

testlink:
  build: .
